sudo: required

 language: python

 python:
  - "2.7"

 services:
  - docker

 cache:
  directories:
  - $HOME/.m2

 before_install:
  - git clone --recurse-submodules git://github.com/openmicroscopy/omero-test-infra .omero

 script:
  - .omero/docker lib
